### ISSUE TITLE
Produce initial tag specification

### ISSUE THREAD

**Issue by abernix** [apollographql/specs-tag#2]
## Requirements

- [x] #1 
- [x] Version it as appropriate
- [x] Setup the Netlify deployment
- [x] https://github.com/apollographql/specs/pull/17
- [x] Publish it (When the PR is landed it should be merged into a version branch to make it official and available at the expected URL.
- [x] Make this repository public

Similar spirit to apollographql/specs-inaccessible#2

**Comment by trevor-scheer** [comment]
All ✅'s ✅ed!
